### ISSUE TITLE
Invalid reporter error

### ISSUE THREAD

**Issue by bcessa** [yamadapc/mocha-spec-cov-alt#1]
Hi there, I'm trying to use this reporter but I keep getting an "invalid reporter" error message, the versions I'm using right now are:

mocha: 1.18.2
blanket: 1.1.6

Running `mocha --require blanket -R html-conv` works just fine; but trying this one gives me the following error:

**mocha --require blanket -R mocha-spec-cov-alt**

```
/usr/local/lib/node_modules/mocha/lib/mocha.js:137
    if (!_reporter) throw new Error('invalid reporter "' + reporter + '"');
                          ^
Error: invalid reporter "mocha-spec-cov-alt"
    at Mocha.reporter (/usr/local/lib/node_modules/mocha/lib/mocha.js:137:27)
    at Object.<anonymous> (/usr/local/lib/node_modules/mocha/bin/_mocha:184:7)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

**Comment by yshnaviganapathi** [comment]
can anyone explain plz i am getting this error while trying to get the reports from mocha chai.

"mocha-simple-html-reporter" reporter not found
/usr/local/lib/node_modules/mocha/lib/mocha.js:174
      throw new Error('invalid reporter "' + reporter + '"');
      ^

Error: invalid reporter "mocha-simple-html-reporter"
    at Mocha.reporter (/usr/local/lib/node_modules/mocha/lib/mocha.js:174:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/mocha/bin/_mocha:311:7)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

**Comment by kinghemantraj** [comment]
i got same issue.
